#!/bin/sh
$CLANG_PATH/bin/clang $* -fuse-ld=lld \
  --target=i686-linux-android \
  --sysroot=$NDK_PATH/platforms/android-29/arch-x86 \
  -L$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/i686-linux-android/4.9.x \
  -L$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android \
  -isystem $NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include \
  -isystem $NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/i686-linux-android
