#!/bin/sh
$CLANG_PATH/bin/clang $* -fuse-ld=lld \
  --target=aarch64-linux-android \
  --sysroot=$NDK_PATH/../platforms/install/platforms/android-29/arch-arm64 \
  -L$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x \
  -L$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android \
  -isystem $NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include \
  -isystem $NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android
