[package]
name = "tt"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
smol_str = "0.1"

stdx = { path = "../stdx", version = "0.0.0" }
