language: rust
dist: xenial
cache:
  cargo: false
os:
  - linux
  - osx
  - windows
rust:
  - nightly
install:
  - rustup component add rustfmt
  # Required for Racer autoconfiguration
  - rustup component add rust-src
  - rustup component add rust-analysis
script:
  # Since the rls-* subcrates use crates.io-based dependencies of themselves it
  # makes sense to test them in isolation rather than just RLS itself
  - (cd rls-analysis && cargo test -v && cargo fmt -- --check)
  - (cd rls-blacklist && cargo test -v && cargo fmt -- --check)
  - (cd rls-data && cargo test -v && cargo fmt -- --check)
  - (cd rls-rustc && cargo test -v && cargo fmt -- --check)
  - (cd rls-span && cargo test -v && cargo fmt -- --check)
  - (cd rls-vfs && cargo test -v && cargo fmt -- --check)
  - cargo fmt -- --check
  - cargo build -v
  - cargo test -v
  - cargo test test_tooltip_std -- --ignored

env:
  global:
    - RUST_BACKTRACE=1
    - RLS_TEST_WAIT_FOR_AGES=1
    - CARGO_INCREMENTAL=0
